-- 000009_enrich_seed_descriptions.down.sql
-- Reverts the descriptions back to the short text shipped in 000008 so the
-- migration is fully reversible. Only touches seeded products.
UPDATE products SET description = 'Premium over-ear headphones with active noise cancellation, 30h battery life and crystal-clear voice calls.' WHERE id = 'seed_elec_001';
UPDATE products SET description = 'Vivid HDR10+ display with built-in streaming apps and voice remote.' WHERE id = 'seed_elec_002';
UPDATE products SET description = '24MP APS-C mirrorless camera with 4K video and in-body stabilization.' WHERE id = 'seed_elec_003';
UPDATE products SET description = 'Hot-swappable switches, per-key RGB and a detachable USB-C cable.' WHERE id = 'seed_elec_004';
UPDATE products SET description = 'IPX7 waterproof speaker with 24h playtime and stereo pairing.' WHERE id = 'seed_elec_005';
UPDATE products SET description = 'Always-on AMOLED, ECG, SpO2, GPS and a 7-day battery.' WHERE id = 'seed_elec_006';
UPDATE products SET description = 'Soft 100% organic cotton tee, sustainably produced.' WHERE id = 'seed_fash_001';
UPDATE products SET description = 'Full-grain leather, satin-lined biker cut with YKK zippers.' WHERE id = 'seed_fash_002';
UPDATE products SET description = 'Breathable mesh upper with responsive foam midsole.' WHERE id = 'seed_fash_003';
UPDATE products SET description = 'Stretch denim with a tailored slim leg and dark wash.' WHERE id = 'seed_fash_004';
UPDATE products SET description = 'Timeless overcoat in a warm wool-blend fabric.' WHERE id = 'seed_fash_005';
UPDATE products SET description = 'Polarized lenses, UV400 protection, lightweight metal frame.' WHERE id = 'seed_fash_006';
UPDATE products SET description = 'Tri-ply stainless steel pots and pans, induction compatible.' WHERE id = 'seed_home_001';
UPDATE products SET description = '15-bar pump espresso machine with milk frother.' WHERE id = 'seed_home_002';
UPDATE products SET description = 'LIDAR navigation, app control, self-charging.' WHERE id = 'seed_home_003';
UPDATE products SET description = 'Ventilated memory foam, hypoallergenic bamboo cover.' WHERE id = 'seed_home_004';
UPDATE products SET description = 'Digital touch panel, 8 presets, dishwasher-safe basket.' WHERE id = 'seed_home_005';
UPDATE products SET description = '16M colors, music sync, works with Alexa & Google Home.' WHERE id = 'seed_home_006';
UPDATE products SET description = '20% L-ascorbic acid serum with hyaluronic acid and vitamin E.' WHERE id = 'seed_beau_001';
UPDATE products SET description = '1800W ionic motor with 3 heat settings and cool shot.' WHERE id = 'seed_beau_002';
UPDATE products SET description = 'Floral-amber fragrance for evening wear.' WHERE id = 'seed_beau_003';
UPDATE products SET description = 'Reef-safe, lightweight, non-greasy daily sunscreen.' WHERE id = 'seed_beau_004';
UPDATE products SET description = 'Sonic 40k vibrations/min with 5 modes and pressure sensor.' WHERE id = 'seed_beau_005';
UPDATE products SET description = 'Cleanser, toner and moisturizer trio for all skin types.' WHERE id = 'seed_beau_006';
UPDATE products SET description = 'Eco-friendly TPE mat with alignment lines and carry strap.' WHERE id = 'seed_sprt_001';
UPDATE products SET description = 'Quick-select pair from 2.5 to 25kg in 2.5kg increments.' WHERE id = 'seed_sprt_002';
UPDATE products SET description = 'MIPS-compatible helmet with 24 vents and removable visor.' WHERE id = 'seed_sprt_003';
UPDATE products SET description = 'Lightweight quick-dry shorts with phone pocket.' WHERE id = 'seed_sprt_004';
UPDATE products SET description = 'Match-grade ball with hand-stitched panels.' WHERE id = 'seed_sprt_005';
UPDATE products SET description = 'Heart rate, sleep and 14 sport modes with 10-day battery.' WHERE id = 'seed_sprt_006';
UPDATE products SET description = '20th anniversary edition. Classic guide to software craftsmanship.' WHERE id = 'seed_book_001';
UPDATE products SET description = 'A craftsman''s guide to software structure and design.' WHERE id = 'seed_book_002';
UPDATE products SET description = 'The big ideas behind reliable, scalable, maintainable systems.' WHERE id = 'seed_book_003';
UPDATE products SET description = 'An easy & proven way to build good habits and break bad ones.' WHERE id = 'seed_book_004';
UPDATE products SET description = 'Rules for focused success in a distracted world.' WHERE id = 'seed_book_005';
UPDATE products SET description = 'A captivating retelling of humankind''s history.' WHERE id = 'seed_book_006';
UPDATE products SET description = 'Compatible with major brick brands, classic colors mix.' WHERE id = 'seed_toys_001';
UPDATE products SET description = 'HD camera, GPS return-home, 25-min flight time.' WHERE id = 'seed_toys_002';
UPDATE products SET description = 'Premium FSC-certified plywood with vivid artwork.' WHERE id = 'seed_toys_003';
UPDATE products SET description = 'Hypoallergenic cuddly bear, machine washable.' WHERE id = 'seed_toys_004';
UPDATE products SET description = 'A timeless strategy board game for 2-4 players.' WHERE id = 'seed_toys_005';
UPDATE products SET description = 'Parental controls, 100+ pre-installed learning apps.' WHERE id = 'seed_toys_006';
UPDATE products SET description = '4K front cam, 1080p rear, Wi-Fi and built-in GPS.' WHERE id = 'seed_auto_001';
UPDATE products SET description = 'Boost 8L gas / 6L diesel engines, USB-C output.' WHERE id = 'seed_auto_002';
UPDATE products SET description = 'Auto-stop pressure, LED light, rechargeable battery.' WHERE id = 'seed_auto_003';
UPDATE products SET description = 'Vent-mount magnetic holder, works with all phone sizes.' WHERE id = 'seed_auto_004';
UPDATE products SET description = 'Scratch-free mitt with 4 premium drying towels.' WHERE id = 'seed_auto_005';
UPDATE products SET description = 'Waterproof rooftop carrier for any vehicle.' WHERE id = 'seed_auto_006';
